source 'https://rubygems.org'

gem 'rake'

# Sinatra
gem 'sinatra'
gem 'puma'
gem 'rack-conneg'
gem 'json'

# App configuration
gem 'rufus-scheduler'
gem 'google-api-client'

# DB
gem 'sqlite3'
gem 'activerecord', '~> 5.2'
gem 'sinatra-activerecord'
gem "tilt-jbuilder", ">= 0.4.0", :require => "sinatra/jbuilder"

gem 'chronic'
