source 'https://rubygems.org'

# Sinatra
gem 'sinatra'
gem 'puma'
gem 'rack-conneg'
gem 'json'
gem 'rufus-scheduler'
gem 'google-api-client'

# DB
gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord'
